
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/edu?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678

management:
  endpoints:
    web:
      exposure:
        include: "*"